project: \
	../deploy/images/moving-up.gif \
	../deploy/images/moving-down.gif \
	../deploy/images/did-not-move.gif \
	../deploy/images/new-1.gif \
	../deploy/images/legend.gif \
	../deploy/images/DESC_arrow.gif \
	../deploy/images/ASC_arrow.gif \
	../deploy/images/nie_logo.jpg \


../deploy/images/moving-up.gif : moving-up.gif
../deploy/images/moving-down.gif : moving-down.gif
../deploy/images/did-not-move.gif : did-not-move.gif
../deploy/images/new-1.gif : new-1.gif
../deploy/images/legend.gif : legend.gif
../deploy/images/DESC_arrow.gif : DESC_arrow.gif
../deploy/images/ASC_arrow.gif : ASC_arrow.gif
../deploy/images/nie_logo.jpg : nie_logo.jpg

../deploy/images/%.gif : %.gif
	cp $< ../deploy/images

../deploy/images/%.jpg : %.jpg
	cp $< ../deploy/images

