<xsl:template xmlns:xsl="http://www.w3.org/1999/XSL/Transform" name="suggestions">
	<xsl:for-each select="MODULE_RESULT">
		<!-- This template must align with XML generated by
				nie/sn/SnURLRecord.generateWebmasterSuggestsGoogleOneBoxItem()
		-->
		<a>
			<xsl:attribute name="href">
				<xsl:value-of select="U" />
			</xsl:attribute>
			<b><xsl:value-of select="Field[@name='title']" /></b><br />
		</a>
		<small><xsl:value-of select="Field[@name='summary']" /></small><p />
	</xsl:for-each>
</xsl:template>
