<xsl:template xmlns:xsl="http://www.w3.org/1999/XSL/Transform" name="suggestions">
	<!-- Use preformatted snippet OR format it ourselves here
	-->
	<xsl:choose>
		<!-- Do we see a preformatted payload? -->
		<!-- Look for any field node called "payload" -->
    	<xsl:when test="//MODULE_RESULT/Field[@name='payload']">
    		<!-- SearchTrack payload -->
    		<!-- Note: Google does NOT allow template match= -->
			<xsl:for-each select="//MODULE_RESULT/Field[@name='payload']/*">
				<!--
				<xsl:copy>
					<xsl:apply-templates select="node() | @*"/>
				</xsl:copy>
				-->
				<xsl:copy-of select="node() | @*" />
			</xsl:for-each>
        </xsl:when>
        <!-- Else no, then format it here -->
        <xsl:otherwise>
			<xsl:for-each select="MODULE_RESULT">
				<!-- This template must align with XML generated by
					nie/sn/SnURLRecord.generateWebmasterSuggestsGoogleOneBoxItem()
				-->
				<a>
					<xsl:attribute name="href">
						<xsl:value-of select="U" />
					</xsl:attribute>
					<b><xsl:value-of select="Field[@name='title']" /></b><br />
				</a>
				<small><xsl:value-of select="Field[@name='summary']" /></small><p />
			</xsl:for-each>
        </xsl:otherwise>
	</xsl:choose>
</xsl:template>
